runtime: custom

env: flex

beta_settings:
  cloud_sql_instances: thematic-garage-276021:southamerica-east1:my-db

manual_scaling:
  instances: 1

entrypoint: node app/src/server.js

resources:
  cpu: 1
  memory_gb: 3
  disk_size_gb: 10

network:
  instance_tag: respostajabackend
  name: default
  session_affinity: true

# liveness_check:
#   path: "/liveness_check"
#   check_interval_sec: 30
#   timeout_sec: 10
#   failure_threshold: 2
#   success_threshold: 2

# readiness_check:
#   path: "/readiness_check"
#   check_interval_sec: 20
#   timeout_sec: 16
#   failure_threshold: 2
#   success_threshold: 2
#   app_start_timeout_sec: 300